### ISSUE TITLE
Update pinned dependencies

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1535]
[Dependencies](https://github.com/nextstrain/augur/blob/81badd27e7800b59e1ed7b4e73fa92963322396c/setup.py#L54-L68) are pinned to reduce the need for urgent code compatibility updates on every breaking change from a dependency. We should still be keeping the code compatible with latest versions of dependencies, just at our own pace. Otherwise Augur will become hard to install in environments where users prefer to use latest versions of these dependencies.

This issue aims to go through the list once, but this should be done regularly.

## Tasks

- [x] networkx v3 nextstrain/augur#1534 
- [x] xopen v2 nextstrain/augur#1532
- [ ] numpy v2 nextstrain/augur#1504
- [x] pandas v2 https://github.com/nextstrain/augur/pull/1671
- [x] jsonschema v4 nextstrain/augur#1358 
- [x] Do this programmatically: nextstrain/augur#1538

## References

- [Slack discussion](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1720726469471229)

**Comment by corneliusroemer** [comment]
We could potentially look into dependabot for pip, but first we'd have to migrate away from setup.py towards pyproject.toml - maybe not a bad idea for the long run, but I don't know what side effects/downsides there might be.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pip-and-pip-compile

setup.py is not supported by dependabot.

**Comment by corneliusroemer** [comment]
Actually I might be wrong - setup.py is potentially supported: https://github.com/nextstrain/augur/network/dependencies

**Comment by victorlin** [comment]
Closing this issue since the process of updating pinned dependencies is now automated with dependabot, and there is a specific issue to track the remaining item in this issue's checklist.
