### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1686]
Parent issue: nextstrain/private#109

## Tasks

- [ ] Remove hardcoded references across all Nextstrain repos
    - @victorlin: I think this is just everything that matches [`org:nextstrain "augur/blob/master"`](https://github.com/search?q=org%3Anextstrain+"augur%2Fblob%2Fmaster"&type=code)
- [ ] ?
- [ ] Rename in GitHub settings
- [ ] Broadcast change internally (and externally?)
